local ofs-common

diff --git a/scripts/common/syn/release_bin/afu_synth b/scripts/common/syn/release_bin/afu_synth
--- a/scripts/common/syn/release_bin/afu_synth
+++ b/scripts/common/syn/release_bin/afu_synth
@@ -57,6 +57,7 @@ export OPAE_PLATFORM_ROOT=${OPAE_PLATFORM_ROOT:-"$(dirname -- "${SCRIPT_DIR}")"}
 # PACKAGER environment variable is used by gen_gbs.tcl in the Quartus project
 export PACKAGER=${PACKAGER:-packager}
 GBS_FILE=${GBS_FILE:-$(basename "${AFU_JSON}" .json).gbs}
+GBS_FILE_2=${GBS_FILE_2:-$(basename "${AFU_JSON}" .json)_2.gbs}
 
 if ! "${PACKAGER}" >/dev/null; then
     echo "ERROR: Packager tool '${PACKAGER}' failed to run. Please check \$PATH and installation." 1>&2
@@ -74,6 +75,7 @@ fi
 
 echo "Compiling ${Q_PROJECT} ${Q_PR_REVISION}"
 echo "Generating ${GBS_FILE}"
+echo "Generating ${GBS_FILE_2}"
 echo "=================================="
 
 # Clean up from previous compilation
@@ -102,14 +104,26 @@ if [ ! -f "${QUARTUS_BUILD_DIR}"/output_files/${Q_PR_REVISION}.${Q_PR_PARTITION_
     exit 1
 fi
 
+if [ ! -f "${QUARTUS_BUILD_DIR}"/output_files/${Q_PR_REVISION}.${Q_PR_PARTITION_NAME_2}.gbs ]; then
+    echo "${QUARTUS_BUILD_DIR}/output_files/${Q_PR_REVISION}.${Q_PR_PARTITION_NAME_2}.gbs not found!"
+    exit 1
+fi
+
 if [ ! -f "${GBS_FILE}" ]; then
     ln -s "${QUARTUS_BUILD_DIR}"/output_files/${Q_PR_REVISION}.${Q_PR_PARTITION_NAME}.gbs "${GBS_FILE}"
 fi
+
+if [ ! -f "${GBS_FILE_2}" ]; then
+    ln -s "${QUARTUS_BUILD_DIR}"/output_files/${Q_PR_REVISION}.${Q_PR_PARTITION_NAME_2}.gbs "${GBS_FILE_2}"
+fi
+
+
 
 echo ""
 echo "==========================================================================="
 echo " PR AFU compilation complete"
 echo " AFU gbs file is '${GBS_FILE}'"
+echo " AFU gbs file is '${GBS_FILE_2}'"
 
 TIMING_SUMMARY_FILE="${QUARTUS_BUILD_DIR}"/output_files/timing_report/clocks.sta.fail.summary
 if [ -s "${TIMING_SUMMARY_FILE}" ]; then
